// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Text_Analysis_BddTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class СравнениеИНагрузочноеТестированиеАлгоритмовСортировкиFeature : object, Xunit.IClassFixture<СравнениеИНагрузочноеТестированиеАлгоритмовСортировкиFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Сравнение и нагрузочное тестирование алгоритмов сортировки", "  Как разработчик высоконагруженной системы,\r\n  Я хочу сравнить производительност" +
                "ь и эквивалентность алгоритмов BubbleSort и BuiltInSort,\r\n  Чтобы убедиться в ид" +
                "ентичности результатов сортировки и выбрать масштабируемое решение.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "03_SortingAlgorithmsLoad.feature"
#line hidden
        
        public СравнениеИНагрузочноеТестированиеАлгоритмовСортировкиFeature(СравнениеИНагрузочноеТестированиеАлгоритмовСортировкиFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Сверка эквивалентности результатов двух алгоритмов на небольших наборах данных")]
        [Xunit.TraitAttribute("FeatureTitle", "Сравнение и нагрузочное тестирование алгоритмов сортировки")]
        [Xunit.TraitAttribute("Description", "Сверка эквивалентности результатов двух алгоритмов на небольших наборах данных")]
        [Xunit.InlineDataAttribute("Uniform", "10", new string[0])]
        [Xunit.InlineDataAttribute("Skewed", "50", new string[0])]
        [Xunit.InlineDataAttribute("Reversed", "100", new string[0])]
        public async System.Threading.Tasks.Task СверкаЭквивалентностиРезультатовДвухАлгоритмовНаНебольшихНаборахДанных(string dataType, string size, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("DataType", dataType);
            argumentsOfScenario.Add("Size", size);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Сверка эквивалентности результатов двух алгоритмов на небольших наборах данных", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync(string.Format("сгенерирован частотный словарь слов типа \"{0}\" размером {1}", dataType, size), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.WhenAsync("выполняется сортировка словаря алгоритмом \"BubbleSort\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.AndAsync("выполняется сортировка словаря алгоритмом \"BuiltInSort\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.ThenAsync("оба алгоритма должны вернуть идентичный порядок пар слово-частота", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Нагрузочное тестирование производительности на больших датасетах")]
        [Xunit.TraitAttribute("FeatureTitle", "Сравнение и нагрузочное тестирование алгоритмов сортировки")]
        [Xunit.TraitAttribute("Description", "Нагрузочное тестирование производительности на больших датасетах")]
        public async System.Threading.Tasks.Task НагрузочноеТестированиеПроизводительностиНаБольшихДатасетах()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Нагрузочное тестирование производительности на больших датасетах", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await testRunner.GivenAsync("сгенерирован большой синтетический датасет со 3000 уникальными словами", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.WhenAsync("замеряется время работы алгоритмов \"BubbleSort\" и \"BuiltInSort\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.ThenAsync("алгоритм \"BuiltInSort\" должен завершиться быстрее чем за 100 миллисекунд", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
    await testRunner.AndAsync("алгоритм \"BuiltInSort\" должен работать быстрее алгоритма \"BubbleSort\" минимум в 5" +
                        " раз", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await СравнениеИНагрузочноеТестированиеАлгоритмовСортировкиFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await СравнениеИНагрузочноеТестированиеАлгоритмовСортировкиFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
